# matrix 
-----
scalar is the basic concept on linear algebra .  
scalar is physical quantity with magnitude. Like length and volume, distance is the scalar.   
Is there a dataset one of the feature is the can measure by magnitude.   

in python `x=3` is looks like scalar. 


In [2]:
x = 2
y = 3
z = x+ y 
print(z)

5


In [3]:
z = x- y 
print(z)


-1


In [4]:
x * y

6

In [5]:
x / y

0.6666666666666666

# vector 
-------
vector is the set of scalar, is devided by magnitude direction.
Vector is not affected by the positions.

vector and zero vector 


In [6]:
# vector (scalar multiplication) 
u = [1,2,3]
v = [4,5,6]

n = len(u)
w = []

for i in range(0, n):
  val = u[i] + v[i]
  w.append(val)

print(w)

[5, 7, 9]


In [7]:
def V_add(u,v):
  """
  vetor multiplication
  input: 1D vector u,v
  output: 1d vector w
  """
  n = len(u)
  w=[]

  for i in range(0,n):
    val = u[i] + v[i]
    w.append(val)

  return w 

In [8]:
V_add(u,v)

[5, 7, 9]

In [9]:
def v_subtract(u,v):
  """
  vector subtractsion
  input: vector u,v
  output: vector w
  """
  n = len(u)
  w=[]

  for i in range(0,n):
    val = u[i] - v[i]
    w.append(val)
  return w

In [10]:
v_subtract(u,v)

[-3, -3, -3]

In [11]:
u=[2,3,4]
a=3

n=len(u)
w=[]

for i in range(0,n):
  val=a*u[i]
  w.append(val)

In [12]:
w

[6, 9, 12]

In [13]:
def v_mul(u,v):
  n=len(u)
  w=[]
  for i in range(0,n):
    val=u[i] * v[i]
    w.append(val)
  return w

In [14]:
v_mul(u,v)

[8, 15, 24]

with numpy

In [18]:
%pip install numpy

Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.


In [19]:
import numpy as np 


In [20]:
u = np.array([1,2,3])
v = np.array([4,5,6])
w = u - v

In [21]:
w

array([-3, -3, -3])

In [22]:
a = 3 
u = np.array([1,2,3])
w = a*u
w

array([3, 6, 9])

In [23]:
# vector vector 
u = np.array([1,2,3])
v = np.array([4,5,6])
w = u * v
w

array([ 4, 10, 18])

In [24]:
w = u / v
w

array([0.25, 0.4 , 0.5 ])

In [25]:
A = [[2,7],[3,4],[6,1]]
B = [[1,4],[4,-1],[2,5]]

n = len(A)
p = len(A[0])

res = []
for i in range(0,n):
    row = []
    for j in range(0,p):
        val = A[i][j] + B[i][j]
        row.append(val)
    res.append(row)
    


In [26]:
res

[[3, 11], [7, 3], [8, 6]]

In [6]:
def add(A,B):
    """
    adding a matrix
    input: additional vector A, B 
    output: adding result C with A,B 
    """
    n = len(A)
    p = len(A[0])
    res = []
    for i in range(0,n):
        row = []
        for j in range(0,p):
            val = A[i][j] + B[i][j]
            row.append(val)
        res.append(row)
    return res 

In [7]:
A = [[2,7], [3,4], [6,1]]
B = [[1,4], [4,-1], [2,5]]

add(A,B)

[[3, 11], [7, 3], [8, 6]]

In [8]:
def subtract(A,B):
    """
    subtract of matrix
    input: subtract vector A,B
    output: subtract result C with A,B
    """
    n = len(A)
    p = len(A[0])

    res = []
    for i in range(0,n):
        row = []
        for j in range(0,p):
            val = A[i][j] - B[i][j]
            row.append(val)
        res.append(row)
    return res

In [9]:
subtract(A,B)

[[1, 3], [-1, 5], [4, -4]]

In [10]:
def matmul(A,B):
    n=len(A)
    p1 = len(A[0])
    p2 = len(B[0])
    res = []
    for i in range(0,n):
        row=[]
        for j in range(0,p2):
            val =0 
            for k in range(0,p1):
                val += A[i][k] + B[k][j]
            row.append(val)
        res.append(row)
    return res

In [11]:
A = [[2,8],[4,3],[10,8]]
B = [[1,4,9],[9,10,4]]
matmul(A,B)

[[20, 24, 23], [17, 21, 20], [28, 32, 31]]

## numpy example

In [12]:
import numpy as np
A = np.array([[2,4],[5,4],[4,2]])
B = np.array([[9,7],[8,9],[7,1]])
C = A+B

In [13]:
C

array([[11, 11],
       [13, 13],
       [11,  3]])

In [14]:
C = A-B
C

array([[-7, -3],
       [-3, -5],
       [-3,  1]])

In [15]:
m = 4 
A*m

array([[ 8, 16],
       [20, 16],
       [16,  8]])

In [16]:
# multiply AoB 
C = np.multiply(A,B)
C

array([[18, 28],
       [40, 36],
       [28,  2]])

In [17]:
C = np.matmul(A,B)
#error

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 2)

In [18]:
A = [[2,8],[4,3],[10,8]]
B = [[1,4,9],[9,10,4]]
np.matmul(A,B)

array([[ 74,  88,  50],
       [ 31,  46,  48],
       [ 82, 120, 122]])